apiVersion: batch/v1
kind: Job
metadata:
  name: sparkoperator-init
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v1beta2-1.2.0-3.0.0
    kustomize.component: spark-operator
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v1beta2-1.2.0-3.0.0
        kustomize.component: spark-operator
    spec:
      serviceAccountName: spark-operatoroperator-sa
      restartPolicy: Never
      containers:
      - name: main
        image: gcr.io/spark-operator/spark-operator:v1beta2-1.2.0-3.0.0
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/gencerts.sh", "-p", "-n", "kubeflow"]
