apiVersion: v1
kind: Service
metadata:
  name: spark-webhook
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v1beta2-1.2.0-3.0.0
    kustomize.component: spark-operator
spec:
  ports:
    - port: 443
      targetPort: 8080
      name: webhook
  selector:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v1beta2-1.2.0-3.0.0
    kustomize.component: spark-operator
